### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by ComedyTomedy** [holyjak/fulcro-intro-wshop#10]
The [#troubleshooting-other-problems](https://github.com/holyjak/fulcro-intro-wshop#troubleshooting-other-problems) section of the `README` suggests that if Fulcro Inspect is blank, users should try a different version of Chromium. I had this problem and it was enough to enable 3rd party cookies, and I think perhaps that would be a better suggestion.

This is also recommended by the Fulcro Inspect readme (and seems to be a common problem/solution!):

> In case you are having trouble to run the extension on Chrome, try to unblock third part cookies:
> 1. Go to chrome://settings/content/cookies
> 2. Uncheck Block third-party cookies
> 3. Restart browser

**Comment by holyjak** [comment]
Many thanks! Readme updated.
