### ISSUE TITLE
Coding exercises - localhost:9001

### ISSUE THREAD

**Issue by chase-lambert** [holyjak/fulcro-intro-wshop#9]
Maybe there should be short note at the beginning of Part 2: Coding Exercises that one needs to uncomment out the `:dev-http {9001 "resources/public"}` portion of the `shadow-cljs.edn` file to make sure they actually have a running build on `localhost:9001` when moving over to the coding exercises portion of this workshop.

Thanks for putting all of this together, it's been great!

**Comment by holyjak** [comment]
Thank you very much! Pls have a look at https://github.com/holyjak/fulcro-intro-wshop/commit/c0b2117d81e9f18395a87cbc956afb9b86bc1bba
